/**
 * Lugares del Complejo Educativo CIT, segun la leyenda oficial del mapa
 * publicada en complejoeducativocit.ed.cr/campus-cit (numeros 1 al 19), mas
 * la enfermeria, que esta dentro de Primaria.
 *
 * `x` y `y` son la punta del pin sobre la ilustracion oficial del campus
 * (726 x 713). La administracion puede mover cada pin desde el panel; estos
 * valores son los iniciales.
 */

export const LIENZO = { ancho: 726, alto: 713 }

export const CATEGORIAS = {
  academico: {
    nombre: 'Aulas y estudio',
    corto: 'Académico',
    color: '#2f6fb5',
  },
  deporte: { nombre: 'Deporte', corto: 'Deporte', color: '#7a5bd1' },
  recreacion: {
    nombre: 'Juegos y recreación',
    corto: 'Recreación',
    color: '#e07a3f',
  },
  alimentacion: { nombre: 'Comida', corto: 'Comida', color: '#c8901a' },
  naturaleza: {
    nombre: 'Naturaleza y producción',
    corto: 'Naturaleza',
    color: '#2f8f4e',
  },
  servicios: { nombre: 'Servicios', corto: 'Servicios', color: '#039690' },
  administracion: {
    nombre: 'Administración',
    corto: 'Administración',
    color: '#233a7a',
  },
  acceso: { nombre: 'Parqueo y acceso', corto: 'Acceso', color: '#5b6573' },
}

export const LUGARES_CIT = [
  {
    clave: 'recepcion',
    numero: 1,
    nombre: 'Recepción general',
    categoria: 'administracion',
    x: 338,
    y: 290,
    descripcion:
      'Entrada principal del colegio. Aquí se atiende a visitas y familias y se hacen los trámites.',
    horario: 'Lunes a viernes, 6:30 a. m. a 4:30 p. m.',
    restringido: false,
    foto: '/fotos/lugares/recepcion.webp',
  },
  {
    clave: 'preescolar',
    numero: 2,
    nombre: 'Preescolar',
    categoria: 'academico',
    x: 417,
    y: 592,
    descripcion: 'Aulas de materno y transición.',
    horario: 'Lunes a viernes, 7:00 a. m. a 12:00 m. d.',
    restringido: true,
    notaAcceso: 'Solo personal y familias de preescolar.',
    foto: '/fotos/lugares/preescolar.webp',
  },
  {
    clave: 'play-granjita',
    numero: 3,
    nombre: 'Play Granjita',
    categoria: 'recreacion',
    x: 458,
    y: 525,
    descripcion:
      'Zona de juego y granjita para los más pequeños, donde aprenden a cuidar plantas y animales.',
    horario: 'Durante la jornada de preescolar',
    restringido: true,
    notaAcceso: 'Para preescolar, con sus maestras.',
    foto: '/fotos/lugares/granjita.webp',
  },
  {
    clave: 'primaria',
    numero: 4,
    nombre: 'Primaria',
    categoria: 'academico',
    x: 374,
    y: 505,
    descripcion:
      'Edificio de primero a sexto grado. Adentro está la enfermería del colegio.',
    horario: 'Lunes a viernes, 7:00 a. m. a 2:30 p. m.',
    restringido: false,
    foto: '/fotos/lugares/primaria.webp',
  },
  {
    clave: 'multiusos-primaria',
    numero: 5,
    nombre: 'Multiusos de primaria',
    categoria: 'recreacion',
    x: 336,
    y: 600,
    descripcion:
      'Salón multiusos para actividades, actos y clases especiales de primaria.',
    horario: 'Según actividades',
    restringido: false,
    foto: '/fotos/lugares/multiusos-primaria.webp',
  },
  {
    clave: 'area-juegos',
    numero: 6,
    nombre: 'Área de juegos',
    categoria: 'recreacion',
    x: 310,
    y: 540,
    descripcion: 'Juegos al aire libre para los recreos de primaria.',
    horario: 'Recreos de primaria',
    restringido: false,
    foto: '/fotos/lugares/area-juegos.webp',
  },
  {
    clave: 'gimnasio-primaria',
    numero: 7,
    nombre: 'Gimnasio de primaria',
    categoria: 'deporte',
    x: 280,
    y: 502,
    descripcion:
      'Gimnasio techado para Educación Física y actividades de primaria.',
    horario: 'Lunes a viernes, 7:00 a. m. a 3:30 p. m.',
    restringido: false,
    foto: '/fotos/lugares/gimnasio-primaria.webp',
  },
  {
    clave: 'secundaria',
    numero: 8,
    nombre: 'Secundaria',
    categoria: 'academico',
    x: 232,
    y: 357,
    descripcion:
      'Edificio de sétimo a duodécimo, con aulas, laboratorios de cómputo y talleres de las especialidades técnicas.',
    horario: 'Lunes a viernes, 7:00 a. m. a 3:30 p. m.',
    restringido: false,
    foto: '/fotos/lugares/secundaria.webp',
  },
  {
    clave: 'deportes',
    numero: 9,
    nombre: 'Deportes',
    categoria: 'deporte',
    x: 168,
    y: 460,
    descripcion:
      'Complejo deportivo con piscina y gimnasio de secundaria. Aquí se entrena natación, voleibol y baloncesto.',
    horario: 'Lunes a viernes, 7:00 a. m. a 4:30 p. m.',
    restringido: false,
    foto: '/fotos/lugares/deportes.webp',
  },
  {
    clave: 'cancha-natural',
    numero: 10,
    nombre: 'Cancha natural',
    categoria: 'deporte',
    x: 411,
    y: 185,
    descripcion: 'Cancha de fútbol de zacate natural.',
    horario: 'Según el horario de Educación Física',
    restringido: false,
    foto: '/fotos/lugares/cancha.webp',
  },
  {
    clave: 'soda',
    numero: 11,
    nombre: 'Soda',
    categoria: 'alimentacion',
    x: 422,
    y: 275,
    descripcion:
      'Desayunos, almuerzos, bebidas y meriendas. Pedí desde CitX y retirá en el recreo sin hacer fila.',
    horario: 'Lunes a viernes, 6:45 a. m. a 3:00 p. m.',
    restringido: false,
    foto: '/fotos/lugares/soda.webp',
  },
  {
    clave: 'parqueo',
    numero: 12,
    nombre: 'Parqueo general',
    categoria: 'acceso',
    x: 473,
    y: 297,
    descripcion: 'Parqueo para personal, familias y visitas.',
    horario: 'Lunes a viernes, 6:00 a. m. a 5:00 p. m.',
    restringido: false,
    foto: '/fotos/lugares/parqueo.webp',
  },
  {
    clave: 'armonia',
    numero: 13,
    nombre: 'Armonía',
    categoria: 'naturaleza',
    x: 582,
    y: 535,
    descripcion: 'Proyecto de agricultura orgánica integrada del colegio.',
    horario: 'Lunes a viernes',
    restringido: false,
    foto: '/fotos/lugares/armonia.webp',
  },
  {
    clave: 'cacaotal',
    numero: 14,
    nombre: 'El Cacaotal (restaurante)',
    categoria: 'alimentacion',
    x: 604,
    y: 461,
    descripcion: 'Restaurante del complejo.',
    horario: 'Consultá el horario en recepción',
    restringido: false,
    foto: '/fotos/lugares/cacaotal.webp',
  },
  {
    clave: 'armonia-tienda',
    numero: 15,
    nombre: 'Armonía (tienda)',
    categoria: 'servicios',
    x: 574,
    y: 486,
    descripcion:
      'Tienda con productos de Armonía, la agricultura orgánica del colegio.',
    horario: 'Consultá el horario en recepción',
    restringido: false,
    foto: '/fotos/lugares/armonia-tienda.webp',
  },
  {
    clave: 'el-chirel',
    numero: 16,
    nombre: 'El Chirel (salón de eventos)',
    categoria: 'servicios',
    x: 515,
    y: 482,
    descripcion: 'Salón de eventos, actos, graduaciones y presentaciones.',
    horario: 'Según actividades',
    restringido: false,
    foto: '/fotos/lugares/chirel.webp',
  },
  {
    clave: 'hospital-veterinario',
    numero: 17,
    nombre: 'Hospital veterinario',
    categoria: 'servicios',
    x: 262,
    y: 203,
    descripcion: 'Hospital veterinario del complejo.',
    horario: 'Consultá el horario en recepción',
    restringido: true,
    notaAcceso: 'Solo con autorización del personal a cargo.',
    foto: '/fotos/lugares/veterinario.webp',
  },
  {
    clave: 'vivero-retono',
    numero: 18,
    nombre: 'Vivero Retoño',
    categoria: 'naturaleza',
    x: 606,
    y: 598,
    descripcion:
      'Vivero donde se producen plantas para el campus y los proyectos ambientales.',
    horario: 'Con actividades guiadas',
    restringido: false,
    foto: '/fotos/lugares/vivero.webp',
    ubicacionAproximada: true,
  },
  {
    clave: 'jardin-etnobotanico',
    numero: 19,
    nombre: 'Jardín Etnobotánico',
    categoria: 'naturaleza',
    x: 640,
    y: 530,
    descripcion:
      'Jardín con plantas medicinales y de uso tradicional, para aprender sobre su historia y cuidado.',
    horario: 'Con actividades guiadas',
    restringido: false,
    foto: '/fotos/lugares/jardin.webp',
    ubicacionAproximada: true,
  },
  {
    clave: 'enfermeria',
    numero: null,
    nombre: 'Enfermería',
    categoria: 'servicios',
    x: 336,
    y: 448,
    descripcion:
      'Dentro del edificio de Primaria. Primeros auxilios, control de signos vitales y apoyo en emergencias de salud.',
    horario: 'Lunes a viernes, 7:00 a. m. a 3:30 p. m.',
    restringido: false,
    foto: '/fotos/lugares/enfermeria.webp',
  },
]
